config/routes.rb
Rails.application.routes.draw do
  # get 'estimates/new'
  # get 'estimates/edit'
  # get 'estimates/index'
  # get 'estimates/show'
  resources :estimates
  resources :estimate_details
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :price_tables, only: [:index, :create, :update, :destroy]
  # resources :masters, only: [:index]
  devise_for :users
  root 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # jqueryで選択されたアイテムの仕様を取得
  get 'estimates/estimate_details/get_details', to: 'estimate_details#details'
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  REGISTRABLE_ATTRIBUTES = %i[user_id subject customer_name].freeze
  TAX_RATE = 10

  belongs_to :user
  # has_many :estimate_details, dependent: :destroy
  has_many :estimate_categories, dependent: :destroy

  # accepts_nested_attributes_for :estimate_details, allow_destroy: true
  accepts_nested_attributes_for :estimate_categories, allow_destroy: true
  # before_validation :calculate_estimate_price

  validates :subject, presence: true
  validates :customer_name, presence: true

  def calculate_total
    # binding.pry
    self.subtotal = estimate_categories.map(&:subtotal).compact.sum
    self.consumption_tax = subtotal * TAX_RATE / 100
    self.grand_total = subtotal + consumption_tax
    self.save
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: %i[show edit update destroy]

  def index
    @estimates = current_user.estimates
  end

  def show
    @estimate_categories = @estimate.estimate_categories
    @active_category = if params[:estimate_category_id]
                         @estimate_categories.find(params[:estimate_category_id])
                       else
                         @estimate_categories.first
                       end
    # @active_category = params[:estimate_category_id]
    # ?  @estimate_categories.find(params[:estimate_category_id]) : @estimate_categories.first
    @estimate_details = @active_category.estimate_details if @active_category
    # @estimate_detail = @active_category.estimate_details.build
    @estimate_detail = EstimateDetail.new(estimate_category_id: @active_category)
  end

  def new
    @estimate = Estimate.new
  end

  def create
    @estimate = Estimate.new(estimate_params)
    # binding.pry
    if @estimate.save
      redirect_to estimates_path, success: "見積 #{@estimate.subject}を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    # binding.pry
    if @estimate.update(estimate_params)
      flash[:success] = '見積を更新しました'
      redirect_to edit_estimate_path(@estimate)
    else
      flash.now[:danger] = '見積更新できませんでした'
      render :edit
    end
  end

  def destroy
    if @estimate.destroy
      flash[:success] = '見積を削除しました'
      redirect_to estimates_path
    else
      flash.now[:danger] = '見積を削除できませんでした'
      render :estimates_path
    end
  end

  private

    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # def estimate_params
    #   params
    #     .require(:estimate)
    #     .permit(
    #       Estimate::REGISTRABLE_ATTRIBUTES +
    #       [estimate_details_attributes: EstimateDetail::REGISTRABLE_ATTRIBUTES]
    #     )
    # end
    def estimate_params
      params
        .require(:estimate)
        .permit(
          Estimate::REGISTRABLE_ATTRIBUTES +
          [estimate_categories_attributes: EstimateCategory::REGISTRABLE_ATTRIBUTES]
        )
    end
end

app/views/estimates/_estimate_category_fields.html.erb
<tr class="nested-fields">
  <%= f.hidden_field :id %>
  <td>
  <%#= f.text_field :name, class: 'form-control' %>
  <%= f.collection_select :category_id, selectable_categories, :id, :name, {}, class: 'form-control' %>
  </td>
  <td>
  <%= f.text_field :subtotal, class: 'form-control subtotal', disabled: true %>
  </td>
  <td>
  <%= link_to_remove_association '削除', f, class: 'btn btn-default' %>
  </td>
</tr>

app/views/estimates/_estimate_detail_fields.html.erb
<tr class="nested-fields">
  <%= f.hidden_field :id %>
  <td>
  <%= f.collection_select :category_id, f.object.selectable_categories(current_user.id), :id, :name, {}, class: 'form-control' %>
  </td>
  <td>
  <%= f.text_field :item_name, class: 'form-control unit-price' %>
  </td>
  <td>
  <%= f.text_field :specification, class: 'form-control unit-price' %>
  </td>
  <td>
  <%= f.text_field :unit, class: 'form-control unit-price' %>
  </td>
  <td>
  <%= f.text_field :unit_price, class: 'form-control unit-price' %>
  </td>
  <td>
  <%= f.text_field :quantity, class: 'form-control quantity' %>
  </td>
  <td>
  <%= f.text_field :price, class: 'form-control subtotal', disabled: true %>
  </td>
  <td>
  <%= f.text_field :remark, class: 'form-control unit-price' %>
  </td>
  <td>
  <%= link_to_remove_association '削除', f, class: 'btn btn-default' %>
  </td>
</tr>

app/views/estimates/_form.html.erb
<%= form_for(estimate, url: path, method: method) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <label class="control-label" for="">見積名称</label>
  <%= f.text_field :subject, class: 'form-control' %>

  <label class="control-label" for="">顧客名</label>
  <%= f.text_field :customer_name, class: 'form-control' %>

  <b>見積明細</b>
  <div class="text-right">
    <%= link_to_add_association '明細を追加', f, :estimate_details,
      class: 'btn btn-default',
      data: {
        association_insertion_node: '#detail-association-insertion-point',
        association_insertion_method: 'append' }
     %>
  </div>

  <table class="table table-list">
    <thead>
      <tr>
        <th>カテゴリー</th>
        <th>商品名</th>
        <th>仕様</th>
        <th>単位</th>
        <th>単価</th>
        <th>数量</th>
        <th>小計</th>
        <th>備考</th>
        <th></th>
      </tr>
    </thead>

    <tbody id='detail-association-insertion-point'>
    <div class="form-group">
    <%= f.fields_for :estimate_details do |ed| %>
      <%= render 'estimate_detail_fields', f: ed %>
    <% end %>
    </div>
    </tbody>
  </table>

  <label class="control-label" for="">見積合計</label>
  <%= f.text_field :subtotal, class: 'form-control total',
      disabled: true,
      value: number_to_currency(f.object.subtotal) %>

  <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/estimates/_form2.html.erb
<%= form_for(estimate, url: path, method: method) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.label :subject, "見積名称" %>
  <%= f.text_field :subject, class: 'form-control' %>

  <%= f.label :customer_name, "顧客名" %>
  <%= f.text_field :customer_name, class: 'form-control' %>

  <label class="control-label" for="">見積合計</label>
  <%= f.text_field :subtotal, class: 'form-control total',
      disabled: true,
      value: number_to_currency(f.object.subtotal) %>

  <h2 class="mt-4 mb-2">カテゴリー</h2>

  <table class="table table-list">
    <thead>
      <tr>
        <th>カテゴリー</th>
        <th>小計</th>
        <th></th>
      </tr>
    </thead>

    <tbody id='category-association-insertion-point'>
    <div class="form-group">
    <%= f.fields_for :estimate_categories do |ec| %>
      <%= render 'estimate_category_fields', f: ec %>
    <% end %>
    </div>
    </tbody>
  </table>

  <div class="text-left">
    <%= link_to_add_association 'カテゴリーを追加', f, :estimate_categories,
      class: 'btn btn-default',
      data: {
        association_insertion_node: '#category-association-insertion-point',
        association_insertion_method: 'append' }
     %>
  </div>

  <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/estimates/edit.html.erb
<%# binding.pry %>
<%#= render 'form', path: estimate_path(@estimate), method: :put, estimate: @estimate %>
<%= render 'form2', path: estimate_path(@estimate), method: :put, estimate: @estimate %>

app/views/estimates/index.html.erb
<div class="section-title">
<h1>見積一覧</h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>見積名称</th>
      <th>顧客名</th>
      <th>総額</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @estimates.each do |estimate| %>
    <tr>
      <td><%= estimate.subject %></td>
      <td><%= estimate.customer_name %></td>
      <td><%= estimate.grand_total %></td>
      <td>
        <%= link_to "明細", estimate_path(estimate), class:"btn btn-primary" %>
        <%= link_to "編集", edit_estimate_path(estimate), class:"btn btn-primary" %>
        <%= link_to "削除", estimate_path(estimate), method: :delete, class:"btn btn-primary" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/estimates/new.html.erb
<%#= render partial: 'form', locals: {path: estimates_path, method: :post, estimate: @estimate} %>
<%#= render 'form', path: estimates_path, method: :post, estimate: @estimate %>
<%= render 'form2', path: estimates_path, method: :post, estimate: @estimate %>

app/views/estimates/show.html.erb
<h2 class="mt-2 mb-2">基本情報</h2>

顧客名：<%= @estimate.customer_name %>様 <br />
見積内容：<%= @estimate.subject %> <br />
小計：<%= @estimate.subtotal.to_s(:delimited) %>円 <br />
消費税：<%= @estimate.consumption_tax.to_s(:delimited) %>円 <br />
総計：<%= @estimate.grand_total.to_s(:delimited) %>円 <br />

<h2 class="mt-4 mb-2">明細</h2>

<% if @estimate_categories && @active_category %>
  <ul id="categoriesTabs" class="nav nav-tabs justify-content-center">
    <% @estimate_categories.each_with_index do |ec, i| %>
      <%# binding.pry %>
      <% if ec == @active_category %>
        <li role="presentation" class="active">
          <%= link_to estimate_path(@estimate, estimate_category_id: ec.id) do %>
            <button aria-controls="spot-tab" role="tab" class="nav-link active"><%= ec.name %></button>
          <% end %>
        </li>
      <% else %>
        <li role="presentation">
          <%= link_to estimate_path(@estimate, estimate_category_id: ec.id)  do %>
            <button aria-controls="spot-tab" role="tab" class="nav-link "><%= ec.name %></button>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="row">
        <div class="col-2">商品名</div>
        <div class="col-2">仕様</div>
        <div class="col-1">単位</div>
        <div class="col-1">単価</div>
        <div class="col-1">数量</div>
        <div class="col-2">金額</div>
        <div class="col-1">備考</div>
        <div class="col-2">操作</div>
  </div>
<% end %>


<% if @estimate_details %>
<% @estimate_details.each do |ed| %>
  <%= form_for(ed, url: estimate_detail_path(ed), method: :put) do |f| %>
    <div class="form-row">
        <%#= f.hidden_field :id %>
        <div class="form-group col-2">
          <%= f.text_field :item_name, class: 'form-control', readonly: true %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :specification, class: 'form-control', readonly: true %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :unit, class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :unit_price, class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :quantity, class: 'form-control', required: true  %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :price, value: ed.price.to_s(:delimited), class: 'form-control', readonly: true %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :remark, class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.submit '更新',  class: ' btn btn-primary btn-block ' %>
        </div>
        <div class="form-group col-1">
          <%= link_to '削除', estimate_detail_path(ed), method: :delete, class: 'btn btn-secondary btn-block ' %>
        </div>
    </div>
  <% end %>
<% end %>
  <div class="row">
        <div class="col-2"></div>
        <div class="col-2"></div>
        <div class="col-1"></div>
        <div class="col-1"></div>
        <div class="col-1">計</div>
        <div class="col-2"><%= @active_category.subtotal.to_s(:delimited) %>円</div>
        <div class="col-1"></div>
        <div class="col-2"></div>
  </div>
<% end %>

<% if @active_category %>
  <%= form_for(@estimate_detail, url: estimate_details_path, method: :post) do |f| %>
    <div class="form-row">
        <%= f.hidden_field :estimate_category_id, value: @active_category.id %>
        <div class="form-group col-4">
          <%= f.collection_select :price_table_id, selectable_price_tables(@active_category.category), :id, :full_item_name , {}, class: 'form-control', id: 'item-selection', :onchange => "getDetails($(this).val())" %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :specification, id: 'inputSpecification specification-selection', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :unit, id: 'inputUnit', class: 'form-control', required: true %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :unit_price, id: 'inputUnitPrice', class: 'form-control', required: true %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :quantity, id: 'inputQuantity', class: 'form-control', required: true  %>
        </div>
        <div class="form-group col-2">
          <%= f.number_field :price, id: 'inputPrice', class: 'form-control', readonly: true %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :remark, id: 'inputRemark', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.submit '新規登録',  class: ' btn btn-success btn-block' %>
        </div>
    </div>
  <% end %>
<% else %>
  <p>まずは、見積もりで使用するカテゴリーを選択してください。</p>
  <%= link_to "カテゴリー登録へ", edit_estimate_path(@estimate) %>
<% end %>


<script>
  function getDetails(val){
    var price_table_id = val;

    $.ajax({
      url: "estimate_details/get_details",
      type: "GET",
      data: {
        price_table_id: price_table_id
      }
    })
  }
</script>