config/routes.rb
Rails.application.routes.draw do
  # get 'estimates/new'
  # get 'estimates/edit'
  # get 'estimates/index'
  # get 'estimates/show'
  resources :estimates
  resources :estimate_details
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :price_tables, only: [:index, :create, :update, :destroy]
  # resources :masters, only: [:index]
  devise_for :users
  root 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # jqueryで選択されたアイテムの仕様を取得
  get 'estimates/estimate_details/get_details', to: 'estimate_details#details'
end

app/controllers/price_tables_controller.rb
class PriceTablesController < ApplicationController
  before_action :set_price_table, only: %i[update destroy]

  def index
    @categories = current_user.categories.order(name: :asc)
    @active_category = params[:id] ? @categories.find(params[:id]) : @categories.first
    @price_tables = @active_category.price_tables
    @price_table = PriceTable.new(category_id: @active_category.id)
  end

  def create
    # binding.pry
    @price_table = PriceTable.new(price_table_params)
    # binding.pry
    if @price_table.save
      flash[:success] = '登録しました。'
      redirect_to price_tables_path(id: @price_table.category_id)
    else
      render_index('登録に失敗しました。')
    end
  end

  def update
    # binding.pry
    if @price_table.update(price_table_params)
      flash[:success] = '更新しました。'
      redirect_to price_tables_path(id: @price_table.category_id)
    else
      render_index('更新に失敗しました。')
    end
  end

  def destroy
    if @price_table.destroy
      flash[:success] = '削除しました。'
      redirect_to price_tables_path(id: @price_table.category_id)
    else
      render_index('削除に失敗しました。')
    end
  end

  private

    def set_price_table
      @price_table = PriceTable.find(params[:id])
    end

    def price_table_params
      params
        .require(:price_table)
        .permit(:category_id, :price_table_id, :item_name, :specification, :unit, :unit_price, :remark)
      # .merge(user_id: current_user.id)
    end

    def render_index(msg)
      flash.now[:alert] = msg
      @price_tables = current_user.price_tables
      render 'index'
    end
end

app/views/price_tables/_form.html.erb
<%= form_for(price_table, url: price_tables_path, method: :post) do |f| %>
    <div class="form-row">
        <div class="form-group col-2">
          <label for="selectCategory">カテゴリー</label>
          <%= f.collection_select :category_id, f.object.selectable_categories(current_user.id), :id, :name, {}, class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <label for="inputItemName">商品名</label>
          <%= f.text_field :item_name ,id: 'inputItemName', class: 'form-control'%>
        </div>
        <div class="form-group col-2">
          <label for="inputSpecification">仕様</label>
          <%= f.text_field :specification, id: 'inputSpecification', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <label for="inputUnit">単位</label>
          <%= f.text_field :unit, id: 'inputUnit', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <label for="inputUnitPrice">単価</label>
          <%= f.number_field :unit_price, id: 'inputUnitPrice', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <label for="inputRemark">備考</label>
          <%= f.text_field :remark, id: 'inputRemark', class: 'form-control' %>
        </div>
        <%= f.submit '新規登録',  class: 'col-1' %>
      </div>
<% end %>

app/views/price_tables/index.html.erb
  <ul id="categoriesTabs" class="nav nav-tabs justify-content-center">
    <% @categories.each_with_index do |category, i| %>
      <%# binding.pry %>
      <% if category == @active_category %>
        <li role="presentation" class="active">
          <%= link_to price_tables_path(id: category.id) do %>
            <button aria-controls="spot-tab" role="tab" class="nav-link active"><%= category.name %></button>
          <% end %>
        </li>
      <% else %>
        <li role="presentation">
          <%= link_to price_tables_path(id: category.id) do %>
            <button aria-controls="spot-tab" role="tab" class="nav-link "><%= category.name %></button>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
 

<table class="table table-list">
  <thead>
    <tr>
      <th>カテゴリー</th> 
      <th>商品名</th>
      <th>仕様</th>
      <th>単位</th>
      <th>単価</th>
      <th>備考</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
  </tbody>
</table>
<% @price_tables.each do |pt|%>
  <%= form_for(pt, url: price_table_path(pt), method: :put) do |f| %>
    <div class="form-row">
        <%#= f.hidden_field :id %>
        <div class="form-group col-2">
          <%= f.collection_select :category_id, f.object.selectable_categories(current_user.id), :id, :name, {}, class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :item_name ,id: 'inputItemName', class: 'form-control'%>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :specification, id: 'inputSpecification', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :unit, id: 'inputUnit', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :unit_price, id: 'inputUnitPrice', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :remark, id: 'inputRemark', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.submit '更新',  class: ' btn btn-primary btn-block ' %>
        </div>
        <div class="form-group col-1">
          <%= link_to '削除', price_table_path(pt), method: :delete, class: 'btn btn-secondary btn-block ' %>
        </div>
    </div>
  <% end %>
<% end %>


  <%= form_for(@price_table, url: price_tables_path, method: :post) do |f| %>
    <div class="form-row">
        <%#= f.hidden_field :id %>
        <div class="form-group col-2">
          <%= f.collection_select :category_id, f.object.selectable_categories(current_user.id), :id, :name, {}, class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :item_name ,id: 'inputItemName', class: 'form-control'%>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :specification, id: 'inputSpecification', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.text_field :unit, id: 'inputUnit', class: 'form-control' %>
        </div>
        <div class="form-group col-1">
          <%= f.number_field :unit_price, id: 'inputUnitPrice', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.text_field :remark, id: 'inputRemark', class: 'form-control' %>
        </div>
        <div class="form-group col-2">
          <%= f.submit '新規登録',  class: ' btn btn-success btn-block' %>
        </div>
    </div>
  <% end %>