config/routes.rb
Rails.application.routes.draw do
  # get 'estimates/new'
  # get 'estimates/edit'
  # get 'estimates/index'
  # get 'estimates/show'
  resources :estimates
  resources :estimate_details
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :price_tables, only: [:index, :create, :update, :destroy]
  # resources :masters, only: [:index]
  devise_for :users
  root 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # jqueryで選択されたアイテムの仕様を取得
  get 'estimates/estimate_details/get_details', to: 'estimate_details#details'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><span><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if user_signed_in? %>
      <div class="navbar-nav">
      <%= link_to 'カテゴリ登録', categories_path, class: "nav-link nav-item" %>
      <%= link_to '単価表登録', price_tables_path, class: "nav-link nav-item" %>
      <%= link_to '見積一覧', estimates_path, class: "nav-link nav-item"  %>
      <%= link_to '見積を新規作成', new_estimate_path, class: "nav-link nav-item"  %>
      </div>
    <% end %>
  </div>
    <div class="navbar-nav">
      <% if user_signed_in? %>
        <p class="nav-item nav-link my-auto mr-4">ログインユーザ： @<%= current_user.nickname %></p>
        <%= link_to 'プロフィール変更', edit_user_registration_path, class: "nav-link nav-item" %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link nav-item"  %>
      <% else %>
        <%= link_to 'サインアップ', new_user_registration_path, class: "nav-link nav-item" %>
        <%= link_to 'ログイン', new_user_session_path, class: "nav-link nav-item" %>
      <% end %>
    </div>
</nav>
</header>