config/routes.rb
Rails.application.routes.draw do
  # get 'estimates/new'
  # get 'estimates/edit'
  # get 'estimates/index'
  # get 'estimates/show'
  resources :estimates
  resources :estimate_details
  resources :categories, only: [:index, :create, :update, :destroy]
  resources :price_tables, only: [:index, :create, :update, :destroy]
  # resources :masters, only: [:index]
  devise_for :users
  root 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # jqueryで選択されたアイテムの仕様を取得
  get 'estimates/estimate_details/get_details', to: 'estimate_details#details'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :price_tables, dependent: :restrict_with_error
  has_many :estimate_categories, dependent: :restrict_with_error

  validates :user_id, uniqueness: { scope: :name }

  scope :sorted, -> { order(name: :asc) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[update destroy]

  def index
    @categories = current_user.categories
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    # binding.pry
    if @category.save
      flash[:success] = '登録しました。'
      redirect_to index
    else
      render_index('登録に失敗しました。')
    end
  end

  # 一括更新時の処理
  # def update
  #   # debugger
  #   # binding.pry
  #   categories_params.each do |id, category_param|
  #     category = Category.find(id)
  #     category.update(category_param)
  #   end
  #   redirect_to masters_path
  # end

  def update
    if @category.update(category_params)
      flash[:success] = '更新しました。'
      redirect_to index
    else
      render_index('更新に失敗しました。')
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = '削除しました。'
      redirect_to index
    else
      render_index("削除に失敗しました。#{@category.errors.full_messages}")
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    # def categories_params
    #   params.permit(categories: %i[id name])[:categories]
    #   # params.require(:categories).permit(:id, :name)
    # end

    def category_params
      params.require(:category).permit(:name).merge(user_id: current_user.id)
    end

    def render_index(msg)
      flash.now[:alert] = msg
      @categories = current_user.categories
      render 'index'
    end
end

app/views/categories/index.html.erb
<%#= form_for(@categories, url: categories_path, method: :post) do |f| %>
<% if false %>
<%= form_tag categories_path, method: "put" do %>
   <table class="table table-list">
    <thead>
      <tr>
        <th>カテゴリー</th>
      </tr>
    </thead>

    <tbody id='detail-association-insertion-point'>

    <div class="form-group">
    <% @categories.each do |category| %>
      <%= fields_for "categories[]", category do |fi| %>
        <%= fi.text_field :name, class: 'form-control mt-2' %>
      <% end %>
    <% end %>
    </div>
    </tbody>
  </table>

  <%= submit_tag '登録', class: 'btn btn-primary' %>
<% end %>
<% end %>


<% @categories.each do |category|%>
  <%= form_for(category, url: category_path(category), method: :put) do |f| %>
    <div class="form-row">
      <div class="form-group col-4">
        <%= f.text_field :name, class: 'form-control'%>
      </div>
      <div class="form-group col-1">
        <%= f.submit '更新',  class: 'btn btn-primary btn-block' %>
      </div>
      <div class="form-group col-1">
        <%= link_to '削除', category_path(category), method: :delete, class: 'btn btn-secondary btn-block' %>
      </div>
    </div>
  <% end %>
<% end %>



<%= form_for(@category, url: categories_path, method: :post) do |f| %>
  <div class="form-row">
    <div class="form-group col-4">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="col-2">
      <%= f.submit '新規登録',  class: 'btn btn-success btn-block' %>
    </div>
  </div>
<% end %>